export default function cuisineToEmoji(cuisineUniqName: string) {
  switch (cuisineUniqName) {
    case 'low-delivery-fee':
      return '💰';
    case 'deals':
      return '💸';
    case 'stampcard-restaurants':
      return '🎟️';
    case 'breakfast':
      return '🥞';
    case 'burgers':
      return '🍔';
    case 'sandwiches':
      return '🥪';
    case 'chicken':
      return '🍗';
    case 'groceries':
      return '🛒';
    case 'alcohol':
      return '🍺';
    case 'italian':
      return '🇮🇹';
    case 'pizza':
      return '🍕';
    case 'indian':
      return '🇮🇳';
    case 'american':
      return '🇺🇸';
    case 'coffee':
      return '☕';
    case 'desserts':
      return '🍰';
    case 'sushi':
      return '🍣';
    case 'japanese':
      return '🇯🇵';
    case 'chinese':
      return '🇨🇳';
    case 'mexican':
      return '🇲🇽';
    case 'pasta':
      return '🍝';
    case 'turkish':
      return '🇹🇷';
    case 'lebanese':
      return '🇱🇧';
    case 'thai':
      return '🇹🇭';
    case 'vegan':
      return '🌱';
    case 'fish-and-chips':
      return '🐟🍟';
    case 'milkshakes':
      return '🥤';
    case 'noodles':
      return '🍜';
    case 'greek':
      return '🇬🇷';
    case 'british':
      return '🇬🇧';
    case 'korean':
      return '🇰🇷';
    case 'caribbean':
      return '🏝️';
    case 'vietnamese':
      return '🇻🇳';
    case 'argentinian':
      return '🇦🇷';
    default:
      return null;
  }
}
